# Objective: Learn Python basics and perform basic data exploration and cleaning using Pandas.

In [7]:
# Step 1: Load a CSV dataset into a Pandas DataFrame.

In [9]:
import pandas as pd

In [13]:
df=pd.read_csv("C:/Users/pawan/Downloads/archive/Combined_dataset.csv")

In [15]:
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [17]:
# Step2: Explore data (head/tail, shape, columns, data types)

In [31]:
# Through this we can get first 5 rows in the dataFrame
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [33]:
# Through this we can get last 5 rows from the DataFrame
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [35]:
# It prints shows no of rows and columns available in the DataFrame.
print("No.of rows and columns available in the DataFrame are :" ,df.shape)

No.of rows and columns available in the DataFrame are : (1000, 24)

In [37]:
# It prints the Columns that are available in the DataFrame
print("Colums that are available in the DataFrame are : ",df.columns)

Colums that are available in the DataFrame are :  Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [39]:
# It prints the Data Types of each Column 
df.dtypes

product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

In [43]:
# Step3: Handle missing values (identify, fill/drop)

In [45]:
df.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [53]:
 # we will fill columns like discount , seller_name, seller_information where as we will drop columns like 
 # what_customers_said, videos, variations(since data available is less than 50 %)

In [57]:
df['discount']=df['discount'].fillna(df['discount'].mean())

In [59]:
df['seller_name']=df['seller_name'].fillna('Unknown Seller')

In [61]:
df['seller_information']=df['seller_information'].fillna('Un Available')

In [63]:
df=df.drop(columns=['what_customers_said','videos','variations'])

In [65]:
# After dropping and filling Missing values in the DataFrame

In [69]:
print("No.of Missing Values in the DataFrame are : \n",df.isnull().sum())

No.of Missing Values in the DataFrame are :
 product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
seller_name               0
sizes                     0
seller_information        0
best_offer                0
more_offers               0
category                  0
dtype: int64

In [73]:
print("The DataFrame Available is :")
df

The DataFrame Available is :

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,product_details,breadcrumbs,product_specifications,amount_of_stars,seller_name,sizes,seller_information,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""description"":""Navy Blue solid backpackNon-Pa...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",Unknown Seller,"[{""size"":""Onesize""}]",Un Available,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""description"":""Navy Blue backpackNon-Padded h...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",Unknown Seller,"[{""size"":""Onesize""}]",Un Available,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""description"":""Pink solid backpacks Non-padd...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",Unknown Seller,"[{""size"":""S""}]",Un Available,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""description"":""Navy and grey printed backpack...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Compartment Closure"",""...","{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",Unknown Seller,"[{""size"":""Onesize""}]",Un Available,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""description"":""Blue solid bath robe, has a sh...","[{""name"":""Men"",""url"":""https://www.myntra.com/m...","[{""specification_name"":""Body or Garment Size"",...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",Unknown Seller,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",Un Available,{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""description"":""Features:Nothing about the For...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",Unknown Seller,"[{""size"":""Onesize""}]",Un Available,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""description"":""Pack Contains: single watchDis...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",Unknown Seller,"[{""size"":""Onesize""}]",Un Available,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""description"":""Case style: Analogue watch, ha...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Dial Material"",""specif...","{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",Unknown Seller,"[{""size"":""Onesize""}]",Un Available,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""description"":""Pack Contains: single watch D...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",Tru███m R███il,"[{""size"":""Onesize""}]",Sho███o. ███-10█████████enu███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""description"":""Set content: One yoga matColou...","[{""name"":""Unisex"",""url"":""https://www.myntra.co...","[{""specification_name"":""Mat Thickness"",""specif...","{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",Unknown Seller,"[{""size"":""Medium""}]",Un Available,{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [75]:
# Step 4: Perform basic operations (filter rows, select columns)

In [77]:
#Filtering Rows based on Seller_name
df[df['seller_name']!='Unknown Seller']

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,product_details,breadcrumbs,product_specifications,amount_of_stars,seller_name,sizes,seller_information,best_offer,more_offers,category
5,17198778,H&M,Beige & Tan Solid Stoneware Soap Dispenser,4.5,42,1399,53.503982,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/171...,...,"{""description"":""Soap dispenser in glazed stone...","[{""name"":""Unisex"",""url"":""https://www.myntra.co...","[{""specification_name"":""Finish"",""specification...","{""1_star"":2,""2_stars"":2,""3_stars"":0,""4_stars"":...",H &███Hen███ & █████████eta█████████████████████,"[{""size"":""Onesize""}]",Pra███yat███fra█████████PVT███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",bathroom-accessories
11,18346118,Arrabi,Pink & White Graphic 300 TC King Bedsheet with...,0.0,0,3329,74.000000,"""₹865.00""",INR,http://assets.myntassets.com/assets/images/183...,...,"{""description"":""Set Content: 1 King Bedsheet w...","[{""name"":""Unisex"",""url"":""https://www.myntra.co...","[{""specification_name"":""Bed Size"",""specificati...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",Sig███Ove███as,"[{""size"":""Super King""}]",Old███. 2███162█████████o. ███████████████████...,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bedsheets
12,18327434,BELLA CASA,Unisex Blue Bedsheets,0.0,0,1499,73.000000,"""₹404.00""",INR,http://assets.myntassets.com/assets/images/183...,...,"{""description"":""WHAT YOU GET : 1 Double Bedshe...","[{""name"":""Unisex"",""url"":""https://www.myntra.co...","[{""specification_name"":""Bed Size"",""specificati...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",Bel███Cas███ash█████████ail█████████,"[{""size"":""Single""}]",E-1███103███PIP█████████ IN███████████████████...,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bedsheets
18,22409156,Kastner,Women Textured Tang Slim Belt,3.8,9,1399,84.000000,"""₹223.00""",INR,http://assets.myntassets.com/assets/images/224...,...,"{""description"":""Brown textured synthetic leath...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Belt Width"",""specifica...","{""1_star"":2,""2_stars"":0,""3_stars"":0,""4_stars"":...",Kas███r L███her█████████Pvt██████,"[{""size"":""26"",""value"":""26.0in"",""value_name"":""T...",A-5███ADA███R V█████████ De█████████████████████,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",belts
19,18985918,Tommy Hilfiger,Women Navy Blue Embroidered High-Neck Pure Cot...,4.1,11,2999,40.000000,"""₹1,799.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""description"":""Navy blue embroidered bodysuit...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Body or Garment Size"",...","{""1_star"":1,""2_stars"":0,""3_stars"":2,""4_stars"":...",PVH███VIN███ASH█████████TE ███████████████,"[{""size"":""XXS"",""value"":""21.8in"",""value_name"":""...",PVH███vin███ash█████████tdN███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",bodysuit
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
986,17697474,Timex,Women White Dial & Gold Toned Analogue Watch T...,4.9,8,1995,20.000000,"""₹1,596.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""description"":""Pack Contains: single watchDis...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",TIM███T R███IL █████████RIV████████████,"[{""size"":""Onesize""}]","Fla███o. ███, 6█████████y C███████████████████...","{""applicable_on"":""Orders above Rs. 1299 (only ...","[{""offer_name"":""10% Instant Discount on Citi C...",watches
991,2466414,Daniel Klein,Women Brown Analogue Watch DK11467-6,4.4,940,6950,53.000000,"""₹3,266.00""",INR,http://assets.myntassets.com/assets/images/246...,...,"{""description"":""Display: Analogue Movement: Me...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":56,""2_stars"":21,""3_stars"":42,""4_star...",DES███ER ███GRE█████████IA ██████,"[{""size"":""Onesize""}]","Fir███Flo███ Pl█████████, I███████████████████...","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
992,11791782,CASIO,Youth Digital Women Red Digital Watch I117 DW-...,4.6,29,3595,10.000000,"""₹3,235.00""",INR,http://assets.myntassets.com/assets/images/117...,...,"{""description"":""Display: DigitalMovement: Quar...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",Fla███ech███tai███,"[{""size"":""Onesize""}]","3rd███165███th █████████, s███████████████████...","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
993,19322504,V2A,Girls Blue Printed Dial & Pink Straps Digital ...,4.0,6,1599,50.000000,"""₹799.00""",INR,http://assets.myntassets.com/assets/images/193...,...,"{""description"":""Pack Contains: single watch D...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",Br ███erp███es,"[{""size"":""Onesize""}]",Kha███ no███122█████████lhi██████████████████,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.000000,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""description"":""Pack Contains: single watch D...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",Tru███m R███il,"[{""size"":""Onesize""}]",Sho███o. ███-10█████████enu███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches

In [79]:
#Filtering Rows based on Discount(i.e discount>=75)
df[df['discount']>=75]

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,product_details,breadcrumbs,product_specifications,amount_of_stars,seller_name,sizes,seller_information,best_offer,more_offers,category
16,20296382,DREAM WEAVERZ,Grey & Coral Printed 220 TC Glazed Cotton King...,3.8,18,2599,78.0,"""₹2,599.00""",INR,http://assets.myntassets.com/assets/images/202...,...,"{""description"":""Set Content : 1 King bedsheet ...","[{""name"":""Unisex"",""url"":""https://www.myntra.co...","[{""specification_name"":""Bed Size"",""specificati...","{""1_star"":2,""2_stars"":1,""3_stars"":3,""4_stars"":...",Unknown Seller,"[{""size"":""Double Queen""}]",Un Available,{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
17,18346134,Arrabi,Pink & Grey Striped 300 TC King Cotton Bedshee...,4.3,12,6329,76.0,"""₹6,329.00""",INR,http://assets.myntassets.com/assets/images/183...,...,"{""description"":""Set content: 1 king bedsheet w...","[{""name"":""Unisex"",""url"":""https://www.myntra.co...","[{""specification_name"":""Bed Size"",""specificati...","{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",Unknown Seller,"[{""size"":""Super King""}]",Un Available,{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
18,22409156,Kastner,Women Textured Tang Slim Belt,3.8,9,1399,84.0,"""₹223.00""",INR,http://assets.myntassets.com/assets/images/224...,...,"{""description"":""Brown textured synthetic leath...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Belt Width"",""specifica...","{""1_star"":2,""2_stars"":0,""3_stars"":0,""4_stars"":...",Kas███r L███her█████████Pvt██████,"[{""size"":""26"",""value"":""26.0in"",""value_name"":""T...",A-5███ADA███R V█████████ De█████████████████████,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",belts
21,1728397,Mactree,Men Brown Solid Mid-Top Flat Boots,3.9,1727,9060,88.0,"""₹1,087.00""",INR,http://assets.myntassets.com/assets/images/172...,...,"{""description"":""A pair of round-toe brown? fla...","[{""name"":""Footwear"",""url"":""https://www.myntra....","[{""specification_name"":""Ankle Height"",""specifi...","{""1_star"":228,""2_stars"":89,""3_stars"":186,""4_st...",MAX███ IN███NAT██████,"[{""size"":""6"",""value"":""25.1cm"",""value_name"":""To...","21/███10 ███NS █████████4 ,███████████████████...","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",boots
38,21873792,KARATCART,Cubic Zirconia Silver-Plated Wraparound Bracelet,4.6,5,3397,76.0,"""₹815.00""",INR,http://assets.myntassets.com/assets/images/218...,...,"{""description"":""Silver-toned and blue handcraf...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Base Metal"",""specifica...","{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...",KOK███V G███AL █████████,"[{""size"":""Onesize"",""value"":""8.26in"",""value_nam...",Sho███58-███Sec█████████ain███████████████████...,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bracelet
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
965,12987894,AMERICAN EAGLE OUTFITTERS,Women White & Yellow Printed Round Neck T-shirt,4.4,5,1799,80.0,"""₹359.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""description"":""White and Yellow printed T-shi...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...",Wes███ry ███din█████████d_M██████,"[{""size"":""XS"",""value"":""29.0in"",""value_name"":""T...","Gro███ Fl███, N█████████old███████████████████...","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
976,13721540,Art Street,Set Of 3 Brown & Green Monuments Theme Framed ...,3.9,8,3500,84.0,"""₹560.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""description"":""Set content: 3 Wall artsColour...","[{""name"":""Unisex"",""url"":""https://www.myntra.co...","[{""specification_name"":""Features"",""specificati...","{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",EDG███QUA███,"[{""size"":""Onesize""}]",I-6███URA███R I█████████ AR███████████████████...,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",wall-art
982,16295388,LOUIS STITCH,Men Brown Leather Two Fold Wallet,4.4,10,4200,75.0,"""₹1,050.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"{""description"":""Brown solid two fold wallet, ...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Closure"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...",Gun███al ███tch█████████E L█████████,"[{""size"":""Onesize""}]","A-1███ Bl███ A,█████████Lok███████████████████...","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",wallets
983,16295382,LOUIS STITCH,Men Brown & Black Leather Two Fold Wallet,0.0,0,4200,75.0,"""₹1,050.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"{""description"":""Brown solid two fold wallet, ...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Coin Pocket Type"",""spe...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",Gun███al ███tch█████████E L█████████,"[{""size"":""Onesize""}]","A-1███ Bl███ A,█████████Lok███████████████████...","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",wallets
990,9053317,TIMESMITH,Men Black Analogue Watch TSC-008,3.7,304,2499,88.0,"""₹2,499.00""",INR,http://assets.myntassets.com/assets/images/905...,...,"{""description"":""Display: AnalogueMovement: Qua...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":54,""2_stars"":20,""3_stars"":34,""4_star...",Unknown Seller,"[{""size"":""Onesize""}]",Un Available,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches

In [81]:
# Filtering columns(i.e Selecting Only Required Columns)
filtered_df=df[['product_id','title','category','initial_price','discount','final_price']]
filtered_df

,product_id,title,category,initial_price,discount,final_price
0,8376765,Lino Perros,backpacks,3995,58.0,"""₹3,995.00"""
1,9136281,Tommy Hilfiger,backpacks,2899,35.0,"""₹2,899.00"""
2,17633752,Lavie,backpacks,2999,65.0,"""₹2,999.00"""
3,1376949,F Gear,backpacks,1675,52.0,"""₹1,675.00"""
4,13939916,MYTRIDENT,bath-robe,2899,17.0,"""₹2,899.00"""
...,...,...,...,...,...,...
995,13698258,KREDO,watches,11890,50.0,"""₹11,890.00"""
996,16896006,GUESS,watches,8900,45.0,"""₹8,900.00"""
997,1708108,GIORDANO,watches,7950,50.0,"""₹7,950.00"""
998,19280114,Fastrack,watches,3295,20.0,"""₹2,636.00"""
999,18601682,BOLDFIT,yoga-mats,699,31.0,"""₹699.00"""

In [83]:
# Now We try to filter the same columns but only the rows which has discount>=75
filtered_df2=filtered_df[filtered_df['discount']>=75]
filtered_df2

,product_id,title,category,initial_price,discount,final_price
16,20296382,DREAM WEAVERZ,bedsheets,2599,78.0,"""₹2,599.00"""
17,18346134,Arrabi,bedsheets,6329,76.0,"""₹6,329.00"""
18,22409156,Kastner,belts,1399,84.0,"""₹223.00"""
21,1728397,Mactree,boots,9060,88.0,"""₹1,087.00"""
38,21873792,KARATCART,bracelet,3397,76.0,"""₹815.00"""
...,...,...,...,...,...,...
965,12987894,AMERICAN EAGLE OUTFITTERS,tshirts,1799,80.0,"""₹359.00"""
976,13721540,Art Street,wall-art,3500,84.0,"""₹560.00"""
982,16295388,LOUIS STITCH,wallets,4200,75.0,"""₹1,050.00"""
983,16295382,LOUIS STITCH,wallets,4200,75.0,"""₹1,050.00"""
990,9053317,TIMESMITH,watches,2499,88.0,"""₹2,499.00"""

In [85]:
# Step 5:Remove duplicates.

In [87]:
print("No.of Duplicate Rows available in the DataFrame are : ")
df.duplicated().sum()

No.of Duplicate Rows available in the DataFrame are :

0

In [89]:
# Step 6: Create a derived column

In [93]:
# Creating/deriving  a column money_saved, it will indicate amount of money saved by ordering this product
df['money_saved']=df['initial_price']*(df['discount']/100)

In [95]:
print("The final DataFrame available is : ")
df.head()

The final DataFrame available is :

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,breadcrumbs,product_specifications,amount_of_stars,seller_name,sizes,seller_information,best_offer,more_offers,category,money_saved
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",Unknown Seller,"[{""size"":""Onesize""}]",Un Available,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,2317.10
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",Unknown Seller,"[{""size"":""Onesize""}]",Un Available,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1014.65
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",Unknown Seller,"[{""size"":""S""}]",Un Available,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1949.35
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Compartment Closure"",""...","{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",Unknown Seller,"[{""size"":""Onesize""}]",Un Available,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,871.00
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"[{""name"":""Men"",""url"":""https://www.myntra.com/m...","[{""specification_name"":""Body or Garment Size"",...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",Unknown Seller,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",Un Available,{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe,492.83

In [97]:
df.to_csv('Cleaned_Combined_dataset.csv', index=False)